----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "zhCN" then
    return
end

local L = BtWQuests.L
L["AMONG_THE_KYRIAN"] = "身居其中"
L["ARRIVAL_IN_THE_SHADOWLANDS"] = "来到暗影界"
L["ASSAULT_ON_THE_HOUSE_OF_RITUALS"] = "突袭祭仪密院"
L["AVARICE"] = "贪婪"
L["A_GOLDEN_DAWN"] = "金色破晓"
L["A_VESSEL_OF_ARDENWEALD"] = "炽蓝仙野容器"
L["CLOSING_IN"] = "步步逼近"
L["CONFRONTING_SIN"] = "直面原罪"
L["DAUGHTER_OF_THE_NIGHT_WARRIOR"] = "月夜战神之女"
L["DEAL_FOR_A_LOA"] = "给洛阿神灵的交易"
L["DESIRE"] = "欲望"
L["DE_BOSS"] = "老大"
L["DOMINION"] = "统御"
L["DO_NOT_FORGET"] = "不可忘却"
L["DRUST_AND_ASHES"] = "德鲁“死”特"
L["DRUST_TO_DRUST"] = "德鲁斯特归于德鲁斯特"
L["ENVY"] = "嫉妒"
L["FOR_QUEEN_AND_GROVE"] = "为了女王和林地！"
L["GRAND_THEFT_NECROPOLIS"] = "侠盗猎城手"
L["LOYAL_TO_THE_PRIMUS"] = "忠于兵主"
L["NIGHT_WARRIORS_CURSE"] = "月夜战神的诅咒"
L["PHAESTUS_GENESIS_OF_AEONS"] = "费斯图斯，万世之源"
L["RETURN_TO_THE_MAW"] = "重返噬渊"
L["RIGHTEOUS_RETRIBUTION"] = "惩奸除恶"
L["SINFALL"] = "堕罪堡"
L["THE_BELL_TOLLS"] = "钟声"
L["THE_COURT_OF_HARVESTERS"] = "收割者之庭"
L["THE_CROWNED_PRINCE"] = "王子加冕"
L["THE_HORNED_HUNTER"] = "硕角猎人"
L["THE_HOUSE_OF_EYES"] = "锐眼密院"
L["THE_HOUSE_OF_RITUALS"] = "祭仪密院"
L["THE_SEAL_OF_CONTRITION"] = "痛悔印记"
L["THE_WAGES_OF_SIN"] = "罪有应得"
L["TRIAL_OF_ASCENSION"] = "晋升试炼"
