----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "ptBR" then
    return
end

local L = BtWQuests.L
L["AMONG_THE_KYRIAN"] = "Entre os kyrianos"
L["ARRIVAL_IN_THE_SHADOWLANDS"] = "Chegada às Terras Sombrias"
L["ASSAULT_ON_THE_HOUSE_OF_RITUALS"] = "Ataque à Casa dos Rituais"
L["AVARICE"] = "Avareza"
L["A_GOLDEN_DAWN"] = "Aurora dourada"
L["A_VESSEL_OF_ARDENWEALD"] = "Receptáculo de Ardena"
L["CLOSING_IN"] = "Mais perto"
L["CONFRONTING_SIN"] = "Confrontando o pecado"
L["DAUGHTER_OF_THE_NIGHT_WARRIOR"] = "Filha da Guerreira da Noite"
L["DEAL_FOR_A_LOA"] = "Acordo por um loa"
L["DESIRE"] = "Desejo"
L["DE_BOSS"] = "Chefe"
L["DOMINION"] = "Domínio"
L["DO_NOT_FORGET"] = "Não se esqueça"
L["DRUST_AND_ASHES"] = "Drustos e cinzas"
L["DRUST_TO_DRUST"] = "Druste o que drustar"
L["ENVY"] = "Inveja"
L["FOR_QUEEN_AND_GROVE"] = "Pela Rainha e pelo bosque!"
L["GRAND_THEFT_NECROPOLIS"] = "O grande roubo necropolitano"
L["LOYAL_TO_THE_PRIMUS"] = "Leal ao Prócer"
L["NIGHT_WARRIORS_CURSE"] = "Maldição da Guerreira da Noite"
L["PHAESTUS_GENESIS_OF_AEONS"] = "Faesto, Gênese dos Éons"
L["RETURN_TO_THE_MAW"] = "Voltar à Gorja"
L["RIGHTEOUS_RETRIBUTION"] = "Retaliação justa"
L["SINFALL"] = "Pecádia"
L["THE_BELL_TOLLS"] = "Sinos que dobram"
L["THE_COURT_OF_HARVESTERS"] = "A Corte dos Ceifadores"
L["THE_CROWNED_PRINCE"] = "O príncipe coroado"
L["THE_HORNED_HUNTER"] = "O Caçador da Galha"
L["THE_HOUSE_OF_EYES"] = "A Casa dos Olhos"
L["THE_HOUSE_OF_RITUALS"] = "A Casa dos Rituais"
L["THE_SEAL_OF_CONTRITION"] = "O Selo da Contrição"
L["THE_WAGES_OF_SIN"] = "O preço do Pecado"
L["TRIAL_OF_ASCENSION"] = "Teste de ascensão"
