----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "itIT" then
    return
end

local L = BtWQuests.L
L["AMONG_THE_KYRIAN"] = "Tra i Kyrian"
L["ARRIVAL_IN_THE_SHADOWLANDS"] = "Arrivo nelle Terretetre"
L["ASSAULT_ON_THE_HOUSE_OF_RITUALS"] = "Assalto alla Casata dei Rituali"
L["AVARICE"] = "Avarizia"
L["A_GOLDEN_DAWN"] = "Un'alba dorata"
L["A_VESSEL_OF_ARDENWEALD"] = "Un ricettacolo di Selvarden"
L["CLOSING_IN"] = "In avvicinamento"
L["CONFRONTING_SIN"] = "Affronta il peccato"
L["DAUGHTER_OF_THE_NIGHT_WARRIOR"] = "Figlia della Guerriera della Notte"
L["DEAL_FOR_A_LOA"] = "Il patto di un Loa"
L["DESIRE"] = "Desiderio"
L["DE_BOSS"] = "O' capo"
L["DOMINION"] = "Dominio"
L["DO_NOT_FORGET"] = "Non dimenticare"
L["DRUST_AND_ASHES"] = "Drust in cenere"
L["DRUST_TO_DRUST"] = "Misure drustiche"
L["ENVY"] = "Invidia"
L["FOR_QUEEN_AND_GROVE"] = "Per la Regina e il bosco!"
L["GRAND_THEFT_NECROPOLIS"] = "Ladri di necropoli"
L["LOYAL_TO_THE_PRIMUS"] = "Leale verso il Primus"
L["NIGHT_WARRIORS_CURSE"] = "La maledizione della Guerriera della Notte"
L["PHAESTUS_GENESIS_OF_AEONS"] = "Festus, Genesi degli Eoni"
L["RETURN_TO_THE_MAW"] = "Ritorno alla Fauce"
L["RIGHTEOUS_RETRIBUTION"] = "Giusta Vendetta"
L["SINFALL"] = "Oblio del Peccato"
L["THE_BELL_TOLLS"] = "Il rintocco della campana"
L["THE_COURT_OF_HARVESTERS"] = "La Corte dei Mietitori"
L["THE_CROWNED_PRINCE"] = "Il principe incoronato"
L["THE_HORNED_HUNTER"] = "Il Cacciatore Cornuto"
L["THE_HOUSE_OF_EYES"] = "La Casata degli Occhi"
L["THE_HOUSE_OF_RITUALS"] = "La Casata dei Rituali"
L["THE_SEAL_OF_CONTRITION"] = "Il Sigillo del Pentimento"
L["THE_WAGES_OF_SIN"] = "Il salario del peccato"
L["TRIAL_OF_ASCENSION"] = "Prova dell'Ascensione"
