----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "ruRU" then
    return
end

local L = BtWQuests.L
L["AMONG_THE_KYRIAN"] = "Среди кирий"
L["ARRIVAL_IN_THE_SHADOWLANDS"] = "Прибытие в Темные Земли"
L["ASSAULT_ON_THE_HOUSE_OF_RITUALS"] = "Штурм дома Ритуалов"
L["AVARICE"] = "Алчность"
L["A_GOLDEN_DAWN"] = "Золотой рассвет"
L["A_VESSEL_OF_ARDENWEALD"] = "Сосуд Арденвельда"
L["CLOSING_IN"] = "Все ближе"
L["CONFRONTING_SIN"] = "Борьба с грехом"
L["DAUGHTER_OF_THE_NIGHT_WARRIOR"] = "Дочь Ночной Воительницы"
L["DEAL_FOR_A_LOA"] = "Сделка с лоа"
L["DESIRE"] = "Желание"
L["DE_BOSS"] = "Большой босс"
L["DOMINION"] = "Господство"
L["DO_NOT_FORGET"] = "Не забывай"
L["DRUST_AND_ASHES"] = "Друсты и пепел"
L["DRUST_TO_DRUST"] = "Друст к друсту"
L["ENVY"] = "Зависть"
L["FOR_QUEEN_AND_GROVE"] = "За королеву и рощу!"
L["GRAND_THEFT_NECROPOLIS"] = "Великий угон некрополя"
L["LOYAL_TO_THE_PRIMUS"] = "Верность Примасу"
L["NIGHT_WARRIORS_CURSE"] = "Проклятие Ночной Воительницы"
L["PHAESTUS_GENESIS_OF_AEONS"] = "Фест, Творец Вечности"
L["RETURN_TO_THE_MAW"] = "Возвращение в Утробу"
L["RIGHTEOUS_RETRIBUTION"] = "Праведная месть"
L["SINFALL"] = "Грехопад"
L["THE_BELL_TOLLS"] = "Колокольный звон"
L["THE_COURT_OF_HARVESTERS"] = "Двор Жнецов"
L["THE_CROWNED_PRINCE"] = "Коронованный принц"
L["THE_HORNED_HUNTER"] = "Рогатый Охотник"
L["THE_HOUSE_OF_EYES"] = "Дом Глаз"
L["THE_HOUSE_OF_RITUALS"] = "Дом Ритуалов"
L["THE_SEAL_OF_CONTRITION"] = "Печать Раскаяния"
L["THE_WAGES_OF_SIN"] = "Ставки греха"
L["TRIAL_OF_ASCENSION"] = "Испытание перерожденных"
